backend:
  name: github
  repo: westonwellman/audio-review-site
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "category", label: "Category", widget: "select", options: ["Pro Audio", "Synths", "Software", "Albums", "Songs"] }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "body", label: "Body", widget: "markdown" }
